### ISSUE TITLE
Icon 的位置跑掉

### ISSUE THREAD

**Issue by gexMichael** [softice70/amis-admin-demo-vue#1]
![image](https://user-images.githubusercontent.com/22609092/129435304-8155172f-ef2e-4def-a567-a088fad87e9d.png)
是否有可能加上 hearder 的程序范例?
左方
![image](https://user-images.githubusercontent.com/22609092/129435356-4a183761-2675-4f38-8cb5-1edb21417764.png)
右方(参考 ovine)
![image](https://user-images.githubusercontent.com/22609092/129435444-23e430aa-8499-4975-aaea-4d33c346d185.png)

Thanks a lot

**Comment by softice70** [comment]
应该是对amis的需求，您可以获取amis的最新版本试试，如果还有问题，可以在 https://github.com/baidu/amis 这里提问

**Comment by gexMichael** [comment]
Thanks a lot
